name: Tests (PHP)

on: [push]

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

    

      - name: Run composer install
        run: composer install -n --prefer-dist
        working-directory: backend

      - name: Prepare Laravel Application
        run: |
          cp .env.example .env
          php artisan key:generate
        working-directory: backend
        
      - name: start artisan
        run: docker compose up
        working-directory: backend
        
        
      - name: seed database
        run: ./vendor/bin/sail up
        working-directory: backend

      - name: Run tests
        run: php artisan test
        env:
          APP_ENV: testing
        working-directory: backend

      - name: Upload artifacts
        uses: actions/upload-artifact@master
        if: failure()
        with:
          name: Logs
          path: backend/storage/logs
