name: Build and Test

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Test Database Connection
        working-directory: ./backend
        run: nc -zv localhost 5432


      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker environment
        uses: docker/setup-buildx-action@v1

      - name: Build and run using Sail
        working-directory: ./backend
        run: |
          php artisan serve

      - name: Run tests
        working-directory: ./backend
        run: |
          php artisan test
