name: Send email on merge

on:
  push:
    branches:
      - main

jobs:
  send_email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Send email
        uses: dawidd6/action-send-mail@v3.7.2
        with:
          server_address: rijeka.riteh.hr
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: 'Hello'
          body: 'Please pull new changes in the main branch due to merges that occured'
          from: 'mplisic@riteh.hr'
          to: 'mplisic@riteh.hr, lbiskupic@riteh.hr, ppaunovic@riteh.hr, lbursic@riteh.hr' 
